spring:
   profiles.active: dev
---
spring:
   profiles: dev
   datasource:
      url: jdbc:mysql://dohko.mysql.001.master.hualala.com:3306/db_yaoqianshu?useUnicode=true&characterEncoding=utf8&useAffectedRows=true&autoReconnect=true
      username: root
      password: hualaladev
      driver-class-name: com.mysql.jdbc.Driver
   redis:
     host: 127.0.0.1
     port: 6379
     password: root

server:
  port: 8080
---
spring:
   profiles: proj
   datasource:
      url: jdbc:mysql://localhost:3306/mysqltest
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8090
