spring:
   profiles.active: proj
---
spring:
   profiles: dev
   datasource:
      url: jdbc:mysql://localhost:3306/mysqltest
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
   redis:
     host: 127.0.0.1
     port: 6379
     password: root

server:
  port: 8090
---
spring:
   profiles: proj
   datasource:
      url: jdbc:mysql://localhost:3306/mysqltest
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
